-- return {
--   -- Thème OneDark.nvim
--   {
--     "navarasu/onedark.nvim",
--     config = function()
--       require("onedark").setup {
--         style = "Deep", -- ou "light" selon ta préférence
--       }
--       require("onedark").load()
--     end
--   },
-- }
